Push capable (#14)
* Output exit code (#10)
* solution for #7
* parameterize EXIT_CODE
* fix bash function calls; switch to the new docker image
* fix bash array length syntax
* oops need that apt update
* ok now change the test code a bit
* check output is working
* fix bad yml syntax
* is it being set at all?
* use a string instead of an integer
* fix bash logic syntax
* single square brackets are the old way to do logic
* review changes
* add output var info to the readme
* Update demo.cpp
* Revert action to upstream master
* fix dockerfile from image not exist
* solution for #7
* parameterize EXIT_CODE
* fix bash function calls; switch to new docker image
* check output is working
* show me some env vars
* trigger on push events
* switch action to push-capable branch
* echo the JSON that lives on the runner
* use cat instead of echo
* remove backticks
* use alpine while debugging git events
* Revert "use alpine while debugging git events"
This reverts commit fbbb1b5a6f8a80f8d4245ebce07d7048ff74fedd.
* test push compatibility
* provide version input
* docker uses tags
* oops update run_checks.sh
* fix jq args on push
* test push src change
* test src change w/ GH checkout
* fix filename output for push events (w/ checkouts)
* test new comment body
* gotta break that bad habit
* check against src change
* use sed directly instead of sed then cat
* tidy docs lied
* don't know why sed isn't working
* try multiple ARG options
* try to replace the docker file
* maybe without dyn var
* bad domain?
* nope needs a docker:// domain
* reverting changes to docker file FROM
* fix clang-format output to file
* test on src changes
* list clang-fmt warnings per file
* add demo.h and adjust comment body
* make test action use default extensions
* don't checkout repo on test action
* stay in working dir. DL into a hidden file
* organize output better
* adjust output again
* fix output; switch back to checkout repo
* enforce CPP syntax in the filename (no checkout)
* sed taking too much out of the path in clang-tidy out
* that's better (checkout is faster)
* segregate script into functions
* oops uncomment from debugging locally
* show me a long diff
* show me a split diff
* clean-up (ready for PR)
* update readme
* remove the version from user inputs
* only apply clang-tidy checks if it was specified
* switch test action back to upstream
* add version for user input

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,15 +1,22 @@
 name: Test action
 
-on: [pull_request]
+on: [push, pull_request]
 
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      # - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
       - uses: shenxianpeng/cpp-linter-action@master
-        with:
-          style: file
-          extensions: 'cpp'
+        id: linter
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
+
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed > 0
+        run: |
+          echo "Some files failed the linting checks!"
+        # for actual deployment
+        # run: exit 1
